config/routes.rb
RealEstateExchange::Application.routes.draw do
  devise_for :users
    get 'my_estates' => 'estates#my_estates'
    resources :estates do
      get :autocomplete_estate_country, on: :collection
      get :autocomplete_estate_city, on: :collection
      get :autocomplete_estate_district, on: :collection
      get :autocomplete_estate_street, on: :collection
    end

  root 'estates#index'

end

app/models/estate.rb
class Estate < ActiveRecord::Base
  belongs_to :users
  validates_presence_of :title, :country, :city, :district, :street, :house, :area, :price

  has_attached_file :photo, styles: {thumb: "300x300>"},
                  :url  => '/assets/images/:id/:style/:id.:extension' 


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :estates       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/estates_controller.rb
class EstatesController < ApplicationController
  autocomplete :estate, :country,:full => true
  autocomplete :estate, :city,:full => true
  autocomplete :estate, :district,:full => true
  autocomplete :estate, :street,:full => true
  before_action :set_estate, only:[:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy, :my_estates]

  def index  
    @search = Estate.search(params[:q])
    @estates = @search.result(distinct: true)
    @estates = @estates.paginate(page: params[:page], per_page: 5)


    @countries = []
    Estate.all.each do |e|
      @countries << e.country
      @countries.uniq!
      @countries.sort!
    end
  end

  def new
    @estate = current_user.estates.build()
  end

  def create
    @estate = current_user.estates.build(estates_params)
    if @estate.save
      redirect_to estate_path(@estate.id)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @estate.update_attributes(estates_params)
      redirect_to estate_path(@estate.id)
    else
      render 'edit'
    end
  end

  def destroy
    if @estate.destroy
      redirect_to my_estates_path
    end
  end

  def my_estates
    @estates = Estate.where(user_id: current_user.id)
    @estates = @estates.paginate(page: params[:page], per_page: 5)
  end

  private

  def estates_params
    params.fetch(:estate,{}).permit(:title, :country, :city, :district, :street, :house,:flat, :area, :price, :user_id, :photo)
  end  

  def set_estate
    @estate = Estate.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estates_helper.rb
module EstatesHelper

end

app/views/estates/_estates.html.haml
= foundation_paginate @estates
Параметры сортировки:
= sort_link @search, :area, "Площадь", {}, { :remote => true, :method => :get } 
= sort_link @search, :price, "Цена", {}, { :remote => true, :method => :get } 
-@estates.each do |e|
  .panel
    %h5
      %small 
        Добавлено #{e.updated_at.to_s(:created_at_estate_time)}
    - if !e.photo.blank?
      %ul.clearing-thumbs.right.estate-img{"data-clearing" => ""}
        %li.glow
          %a.th.th-item{href: e.photo.url, style:"background-image: url(#{e.photo.url(:thumb)});height: 200px;width: 200px;overflow: hidden;background-position: center;background-repeat: no-repeat;"}
            %img{ src: e.photo.url(:thumb), style:"opacity:0;"}
    %p
      %b Страна:
      = (params[:q] ? highlight(e.country,params[:q][:country_eq]) : e.country) 
    %p      
      %b Описание:
      = (params[:q] ? highlight(e.title,params[:q][:title_eq]) : e.title) 
    %p 
      %b Город:
      = (params[:q] ? highlight(e.city,params[:q][:city_cont]) : e.city) 
    %p 
      %b Район:
      = (params[:q] ? highlight(e.district,params[:q][:district_cont]) : e.district) 
    %p   
      %b Улица:
      = (params[:q] ? highlight(e.street,params[:q][:street_cont]) : e.street) 
    %p 
      %b Дом:
      = (params[:q] ? highlight(e.house,params[:q][:house_cont]) : e.house) 
    %p 
      %b Квартира: 
      = e.flat  
    %p 
      %b Площадь,м2:
      -if params[:q]
        -if params[:q][:area_gteq] || params[:q][:area_lteq]
          = highlight(e.area.to_s,e.area.to_s)
        - else
          = e.area  
      -else
        = e.area 
    %p 
      %b Цена, $:
      -if params[:q]
        -if params[:q][:price_gteq] || params[:q][:price_lteq]
          = highlight(e.price.to_s,e.price.to_s)
        - else
          = e.price  
      -else
        = e.price  

    %p
      %b User_id
      = e.user_id  
    = link_to 'Подробнее', estate_path(id: e.id)  

    - if user_signed_in? && e.user_id == current_user.id
      %hr
      #link_to_delete
        = link_to "Удалить", {controller: :estates, action: :destroy, id: e.id, user_id: current_user.id}, method: :delete, data:{confirm:"Delete?"}
= foundation_paginate @estates   

app/views/estates/_form.html.haml
#inputForm
  = form_for @estate do |f|
    .form
      #country
      = f.label "Описание(квартира, дом, комната)"
      = f.select :title,[['дом'],["квартира"],["комната"]], { :include_blank => '-- Выберите тип --' }, :required => true
      = f.label "Страна"
      = f.autocomplete_field :country, autocomplete_estate_country_estates_path , required: 'required'
      = f.label "Город"
      = f.autocomplete_field :city, autocomplete_estate_city_estates_path , required: 'required'
      = f.label "Район"
      = f.autocomplete_field :district, autocomplete_estate_district_estates_path , required: 'required'
      = f.label "Улица"
      = f.autocomplete_field :street, autocomplete_estate_street_estates_path , required: 'required'
      = f.label "Дом"
      = f.text_field :house, required: 'required'
      = f.label "Квартира"  
      = f.text_field :flat
      = f.label "Площадь,м2"
      = f.text_field :area, required: 'required'
      = f.label "Цена,$"  
      = f.text_field :price, required: 'required'
      = f.label "Фото"
      = f.file_field :photo
      = f.submit "отправить", class: "button radius tiny"

app/views/estates/_search.html.haml
#searchForm
  = search_form_for @search,  remote: true, url: estates_path, method: :get do |f|
    = f.select :country_eq, options_for_select(@countries.collect{|p| p }),include_blank: true,prompt:"Страна"
    = f.autocomplete_field :city_cont, autocomplete_estate_city_estates_path, placeholder:"Город"
    = f.autocomplete_field :district_cont, autocomplete_estate_district_estates_path, placeholder:"Район"
    = f.autocomplete_field :street_cont, autocomplete_estate_street_estates_path, placeholder:"Улица"  
    = f.text_field :price_gteq,placeholder: "Цена, от $"
    = f.text_field :price_lteq,placeholder: "Цена, до $"
    = f.text_field :area_gteq,placeholder: "Площадь, от м2"
    = f.text_field :area_lteq,placeholder: "Площадь, до м2"
    = f.select :title_eq, [["квартира"],["дом"],["комната"]],include_blank: true, prompt:"тип"
    = f.submit 'Поиск', class: "button tiny"
    = f.submit "сброс", type: "reset"

app/views/estates/edit.html.haml
= render "estates/form"

app/views/estates/index.html.haml
-if params[:q]
  %h2.subheader Результаты поиска
  #results
    Найдено: #{@estates.count}
- else  
  %h2.subheader#s Все объявления
  #f
/ = content_tag "div", id: "e", data: {countries: @countries, cities: @cities} do
/   Load
#estates    
  = render "estates"  

app/views/estates/index.js.haml
$("#estates").html("#{escape_javascript ( render('estates')) }")

-if !params[:q].blank?
  $("#s").html("#{escape_javascript ( 'Результаты поиска') }")
  $("#f").html("#{escape_javascript (render text: ( "Найдено: #{@estates.count}") ) }" )

app/views/estates/my_estates.html.haml
= will_paginate @estates, renderer: FoundationPagination::Rails
-@estates.each do |e|
  .panel
    %h5
      %small 
        Добавлено #{e.updated_at.to_s(:created_at_estate_time)}
    - if !e.photo.blank?
      %ul.clearing-thumbs.right.estate-img{"data-clearing" => ""}
        %li.glow
          %a.th.th-item{href: e.photo.url, style:"background-image: url(#{e.photo.url(:thumb)});height: 200px;width: 200px;overflow: hidden;background-position: center;background-repeat: no-repeat;"}
            %img{ src: e.photo.url(:thumb), style:"opacity:0;"}
    %p
      %b Страна:
      = e.country
    %p 
      %b Город:
      = e.city
    %p 
      %b Цена, $:
      = e.price  
    = link_to 'Подробнее', estate_path(id: e.id)  

    - if user_signed_in? && e.user_id == current_user.id
      %hr
      #link_to_delete
        = link_to "Удалить", {controller: :estates, action: :destroy, id: e.id, user_id: current_user.id}, method: :delete, data:{confirm:"Delete?"}
= will_paginate @estates, renderer: FoundationPagination::Rails    

app/views/estates/new.html.haml
= render "estates/form"

app/views/estates/show.html.haml
.panel
  - if !@estate.photo.blank?
    %ul.clearing-thumbs.right{"data-clearing" => ""}
      %li.glow
        %a.th.th-item{href: @estate.photo.url, style:"background-image: url(#{@estate.photo.url(:thumb)});height: 200px;width: 200px;overflow: hidden;background-position: center;background-repeat: no-repeat;"}
          %img{ src: @estate.photo.url(:thumb), style:"opacity:0;"}
  %p
    %b Страна:
    = @estate.country  
  %p      
    %b Описание:
    = @estate.title
  %p 
    %b Город:
    = @estate.city
  %p 
    %b Район:
    = @estate.district
  %p   
    %b Улица:
    = @estate.street
  %p 
    %b Дом:
    = @estate.house
  %p 
    %b Квартира: 
    = @estate.flat    
  %p 
    %b Площадь,м2:
    = @estate.area 
  %p 
    %b Цена, $: 
    = @estate.price


  = link_to "вернуться", :back   
  -if user_signed_in? && @estate.user_id == current_user.id 
    %hr
    %p  
      = link_to "Редактировать", edit_estate_path(@estate.id)   
      #link_to_delete
        = link_to "Удалить",{controller: :estates, action: :destroy, id: @estate.id, user_id: current_user.id}, method: :delete, data:{confirm:"Удалить объявление?"}

app/views/layouts/_header.html.haml
%nav.top-bar{"data-topbar" => "", :role => "navigation"}
  %ul.title-area
    %li.name
      %h1
        = link_to "на главную", root_path
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    %ul.right
      %li
        = link_to "Все объявления", root_path
      - if user_signed_in?
        %li.has-dropdown
          = link_to "Личный кабинет"
          %ul.dropdown
            %li
              = link_to "Настройки", edit_user_registration_path
            %li
              = link_to "Подать объявление", new_estate_path
            %li  
              = link_to "Мои объявления", my_estates_path
            %li.divider
            %li
              = link_to "выход(#{current_user.email})", destroy_user_session_path, :method => :delete
      - else
        %li
          = link_to "Войти", new_user_session_path
        %li
          = link_to "Регистрация", new_user_registration_path          

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "foundation-rails"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    = render "layouts/header"

    .row
      - if current_page?(root_path) || current_page?(controller: '/estates', action: :index)
        .large-3.columns
          = render "estates/search"
        .large-9.columns
          = yield          
      - else 
        .large-12.columns
          = yield          
    = javascript_include_tag "application"